version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: crud_db
    restart: always
    environment:
      MYSQL_DATABASE: 'crud'
      MYSQL_USER: 'root'    
      MYSQL_PASSWORD: 'root'      
      MYSQL_ROOT_PASSWORD: 'root'
    ports:      
      - '3306:3306'
    expose:      
      - '3306'      
    volumes:
      - my-db-crud:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.8.3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret_pass
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  my-db-crud:
  rabbitmq: